package loan;


import database.dataBaseSql;
import fileChooser.FileChooser;
import java.io.IOException;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;
import readExcel.DataExcel;
import regex.RegexSample;
import repository.ReposDataBase;

import repository.ReposExcel;

/**
 *
 * @author ali
 */
public class LoanAdd extends javax.swing.JFrame {

    DateTimeFormatter dtf = DateTimeFormatter.ISO_DATE;
    RegexSample regex = new RegexSample();
    ReposDataBase data = new dataBaseSql();
    FileChooser openChooseFile = new FileChooser();
    private LocalDate hitelkezd = LocalDate.of(00, 01, 01);
    private LocalDate hitelVege = LocalDate.of(00, 01, 01);
    private int LoanAmount = 0;
    private int loanTerm = 0;
    private double loanRate = 0.0;
    private int pCode = 0;
    private int loanValue = 0;
    private int loanSize = 0;
    private int loanValues = 0;
    

    /**
     * Creates new form hitelfelvitele
     */
    public LoanAdd() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        hitelUgyfelid = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        hitelTipus = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        hitelOsszeg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        hitelStart = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        hitelLejaratSzamol = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        hitelKamatlab = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        hitelHrsz = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        hitelIrSzam = new javax.swing.JTextField();
        hitelCim = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        hitelFedezetMeret = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        hitelFedezetAllapot = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        hitelBecsErtek = new javax.swing.JTextField();
        hitelFutamido = new javax.swing.JTextField();
        hitelLejarat = new javax.swing.JTextField();
        loanSaveButton = new javax.swing.JButton();
        lEditButton = new javax.swing.JButton();
        lReadExcel = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        hitelVaros = new javax.swing.JTextField();
        show_validation = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LoanID = new javax.swing.JLabel();
        IDReadButton = new javax.swing.JButton();
        idCheck = new javax.swing.JLabel();
        typeCheck = new javax.swing.JLabel();
        amountCheck = new javax.swing.JLabel();
        startCheck = new javax.swing.JLabel();
        termCheck = new javax.swing.JLabel();
        endCheck = new javax.swing.JLabel();
        rateCheck = new javax.swing.JLabel();
        hrszCheck = new javax.swing.JLabel();
        cityCheck = new javax.swing.JLabel();
        postalcCheck = new javax.swing.JLabel();
        addressCheck = new javax.swing.JLabel();
        sizeCheck = new javax.swing.JLabel();
        valueCheck = new javax.swing.JLabel();
        condCheck = new javax.swing.JLabel();
        deleteButton = new javax.swing.JButton();

        jLabel13.setText("jLabel13");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hitel");
        setBackground(new java.awt.Color(150, 150, 150));

        jLabel1.setText("Hitel hozzáadása ügyfélhez :");

        jLabel2.setText("Ügyfél id :");

        hitelUgyfelid.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        hitelUgyfelid.setMinimumSize(new java.awt.Dimension(10, 50));
        hitelUgyfelid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitelUgyfelidActionPerformed(evt);
            }
        });
        hitelUgyfelid.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelUgyfelidKeyTyped(evt);
            }
        });

        jLabel3.setText("Hitel típusa : ");

        hitelTipus.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelTipusKeyTyped(evt);
            }
        });

        jLabel4.setText("Hitel Összege : ");

        hitelOsszeg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitelOsszegActionPerformed(evt);
            }
        });
        hitelOsszeg.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelOsszegKeyTyped(evt);
            }
        });

        jLabel5.setText("Szerződés kezdete : ");

        hitelStart.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelStartKeyTyped(evt);
            }
        });

        jLabel6.setText("Futamidő (hónap) : ");

        jLabel7.setText("Lejárat : ");

        hitelLejaratSzamol.setText("Számol");
        hitelLejaratSzamol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitelLejaratSzamolActionPerformed(evt);
            }
        });

        jLabel8.setText("Kamatláb : ");

        hitelKamatlab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitelKamatlabActionPerformed(evt);
            }
        });
        hitelKamatlab.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelKamatlabKeyTyped(evt);
            }
        });

        jLabel9.setText("Hitel Fedezet Adatai :");

        jLabel10.setText("Hrsz :");

        hitelHrsz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelHrszKeyTyped(evt);
            }
        });

        jLabel11.setText("Irányítószám :");

        jLabel12.setText("Cím :");

        hitelIrSzam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitelIrSzamActionPerformed(evt);
            }
        });
        hitelIrSzam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelIrSzamKeyTyped(evt);
            }
        });

        hitelCim.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelCimKeyTyped(evt);
            }
        });

        jLabel14.setText("Méret :");

        hitelFedezetMeret.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelFedezetMeretKeyTyped(evt);
            }
        });

        jLabel15.setText("Becsérték :");

        hitelFedezetAllapot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitelFedezetAllapotActionPerformed(evt);
            }
        });
        hitelFedezetAllapot.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelFedezetAllapotKeyTyped(evt);
            }
        });

        jLabel16.setText("Állapot : ");

        hitelBecsErtek.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelBecsErtekKeyTyped(evt);
            }
        });

        hitelFutamido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelFutamidoKeyTyped(evt);
            }
        });

        hitelLejarat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hitelLejaratActionPerformed(evt);
            }
        });
        hitelLejarat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelLejaratKeyTyped(evt);
            }
        });

        loanSaveButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        loanSaveButton.setText("Ment új hitelként");
        loanSaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanSaveButtonActionPerformed(evt);
            }
        });

        lEditButton.setFont(new java.awt.Font("Lucida Grande", 1, 12)); // NOI18N
        lEditButton.setText("Módosít");
        lEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lEditButtonActionPerformed(evt);
            }
        });

        lReadExcel.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        lReadExcel.setText("Beolvasás Fájlból");
        lReadExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lReadExcelActionPerformed(evt);
            }
        });

        jLabel17.setText("Város :");

        hitelVaros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hitelVarosKeyTyped(evt);
            }
        });

        jLabel18.setText("Id: ");

        LoanID.setText("*");

        IDReadButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        IDReadButton.setText("Id beolvasása ");
        IDReadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDReadButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        deleteButton.setText("Töröl");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(loanSaveButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lReadExcel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel18)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LoanID)
                        .addGap(47, 47, 47))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(hitelBecsErtek, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(hitelFedezetMeret, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelCim, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelIrSzam, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelHrsz, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelKamatlab)
                            .addComponent(hitelLejarat, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelTipus, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelOsszeg, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelStart, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelFutamido, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hitelUgyfelid, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hitelFedezetAllapot)
                            .addComponent(hitelVaros))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 113, Short.MAX_VALUE)
                                .addComponent(hitelLejaratSzamol))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idCheck)
                                    .addComponent(typeCheck)
                                    .addComponent(amountCheck)
                                    .addComponent(startCheck)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(postalcCheck)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(show_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(endCheck)
                                    .addComponent(termCheck)
                                    .addComponent(rateCheck)
                                    .addComponent(hrszCheck)
                                    .addComponent(cityCheck)
                                    .addComponent(addressCheck)
                                    .addComponent(sizeCheck)
                                    .addComponent(valueCheck)
                                    .addComponent(condCheck))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(50, 50, 50))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(IDReadButton)
                        .addGap(18, 18, 18)
                        .addComponent(lEditButton, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteButton)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel18)
                    .addComponent(LoanID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(hitelUgyfelid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idCheck))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(hitelTipus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(typeCheck))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hitelOsszeg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(amountCheck))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(hitelStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startCheck))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(hitelFutamido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(termCheck))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel7)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hitelLejarat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hitelLejaratSzamol)
                        .addComponent(endCheck)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(hitelKamatlab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rateCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(hitelHrsz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hrszCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(hitelVaros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(hitelIrSzam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(show_validation, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postalcCheck))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(hitelCim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressCheck))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel14)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(hitelBecsErtek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(valueCheck)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(hitelFedezetMeret, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sizeCheck)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hitelFedezetAllapot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16)
                    .addComponent(condCheck))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(loanSaveButton)
                    .addComponent(lReadExcel)
                    .addComponent(lEditButton)
                    .addComponent(IDReadButton)
                    .addComponent(deleteButton))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hitelFedezetAllapotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitelFedezetAllapotActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hitelFedezetAllapotActionPerformed

    private void hitelUgyfelidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitelUgyfelidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hitelUgyfelidActionPerformed

    private void loanSaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanSaveButtonActionPerformed
      // null check
        if (!hitelStart.getText().isEmpty()) {
            hitelkezd = LocalDate.parse(hitelStart.getText(), dtf);
            hitelVege = hitelkezd.plusMonths(Long.parseLong(hitelFutamido.getText()));
        }       
        if (!hitelUgyfelid.getText().isEmpty()) {
            Integer.parseInt(hitelUgyfelid.getText());
        }
        if (!hitelOsszeg.getText().isEmpty()) {
            LoanAmount = Integer.parseInt(hitelOsszeg.getText());
        }
        if (!hitelFutamido.getText().isEmpty()) {
            loanTerm = Integer.parseInt(hitelFutamido.getText());
        }
        if (!hitelKamatlab.getText().isEmpty()) {
            loanRate = Double.parseDouble(hitelKamatlab.getText());
        }
        if (!hitelIrSzam.getText().isEmpty()) {
            pCode = Integer.parseInt(hitelIrSzam.getText());
        }
        if (!hitelFedezetMeret.getText().isEmpty()) {
            loanSize = Integer.parseInt(hitelFedezetMeret.getText());
        }
        if (!hitelBecsErtek.getText().isEmpty()) {
            loanValues = Integer.parseInt(hitelBecsErtek.getText());
        }


    
                    try{
                          
                    }catch (DateTimeParseException ex){
            JOptionPane.showMessageDialog(rootPane, "Dátum formátum nem megfelelő (ÉÉÉÉ-HH-NN) !" );
                    }           
           
        try {
      
            ReposDataBase insert = new dataBaseSql();
            try {
             
                if (!hitelUgyfelid.getText().isEmpty()) {
                insert.insertLoan(new Loan(Integer.parseInt(hitelUgyfelid.getText()), hitelTipus.getText(), LoanAmount,hitelkezd,hitelVege,
                        loanTerm, loanRate,  hitelHrsz.getText(), hitelVaros.getText(), hitelCim.getText(),
                        pCode, loanSize, loanValues, hitelFedezetAllapot.getText()
                        )); 
                //  public Loan(int ugyfelId, String hitelTipus, int osszeg, LocalDate kezdet, LocalDate lejarat, int futamido, double kamatlab, String hrsz, String fVaros, String fCim, int fIrSzam, int meret, int becsErtek, String allapot) {
                      if (insert.sqlIdCount()!=0) {
                         JOptionPane.showMessageDialog(rootPane, "Az adatok rögzítésre kerültek! Id: "+insert.sqlIdCount());
                      }
            
                } else {
               JOptionPane.showMessageDialog(rootPane, "Az Ügyfél ID nem lehet üres", 
                       "Hiba!",JOptionPane.INFORMATION_MESSAGE); 
            }   
            } catch (NumberFormatException e) {
            }
           
        } catch (SQLException e) {
        }
        
     
    }//GEN-LAST:event_loanSaveButtonActionPerformed

    private void hitelLejaratSzamolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitelLejaratSzamolActionPerformed
     
        try {
   
        
             if (!hitelStart.getText().isEmpty()) {
                    try{
            hitelkezd  =    LocalDate.parse(hitelStart.getText(), dtf);
            hitelVege = hitelkezd.plusMonths(Long.parseLong(hitelFutamido.getText()));
            LocalDate localDate = hitelVege;//For reference
            DateTimeFormatter formatter = DateTimeFormatter.ISO_DATE;
            String formattedString = localDate.format(formatter);
            hitelLejarat.setText(formattedString);
                    }catch (DateTimeParseException ex){
            JOptionPane.showMessageDialog(rootPane, "Dátum formátum nem megfelelő (ÉÉÉÉ-HH-NN) !" );
                    } 
            } 
        } catch (DateTimeParseException e) {
        }
        
    }//GEN-LAST:event_hitelLejaratSzamolActionPerformed

    private void hitelIrSzamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitelIrSzamActionPerformed
        try {
            int irszam = Integer.parseInt(hitelIrSzam.getText());
            show_validation.setText("");
        } catch (NumberFormatException e) {
            show_validation.setText("Nem megelelő formátum");
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_hitelIrSzamActionPerformed

    private void hitelOsszegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitelOsszegActionPerformed
      
        // TODO add your handling code here:
    }//GEN-LAST:event_hitelOsszegActionPerformed

    private void hitelLejaratActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitelLejaratActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hitelLejaratActionPerformed

    private void lReadExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lReadExcelActionPerformed
        try {

            ReposExcel adatok = new DataExcel(openChooseFile.fileChooser());

            for (Loan loanEntries : adatok.findAllLoans()) {
                hitelUgyfelid.setText("" + loanEntries.getUgyfelId());
                hitelTipus.setText(loanEntries.getHitelTipus());
                hitelOsszeg.setText("" + loanEntries.getOsszeg());
                hitelStart.setText("" + loanEntries.getKezdet());
                hitelFutamido.setText("" + loanEntries.getFutamido());
                hitelLejarat.setText("" + loanEntries.getLejarat());
                hitelKamatlab.setText("" + loanEntries.getKamatlab());
                hitelHrsz.setText("" + loanEntries.getHrsz());
                hitelVaros.setText(loanEntries.getfVaros());
                hitelIrSzam.setText("" + loanEntries.getfIrSzam());
                hitelCim.setText("" + loanEntries.getfCim());
                hitelFedezetMeret.setText("" + loanEntries.getMeret());
                hitelBecsErtek.setText("" + loanEntries.getBecsErtek());
                hitelFedezetAllapot.setText("" + loanEntries.getAllapot());
            }
              // regex check

        if (regex.StrCheck(regex.REGEXONLYNUMBER, hitelUgyfelid.getText())) {
            idCheck.setIcon(regex.getIconeOk());

        } else {
            idCheck.setIcon(regex.getIconeX());

        }
        if (regex.StrCheck(regex.REGEXNAME, hitelTipus.getText())) {
            typeCheck.setIcon(regex.getIconeOk());

        } else {
            typeCheck.setIcon(regex.getIconeX());
        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, hitelOsszeg.getText())) {
            amountCheck.setIcon(regex.getIconeOk());

        } else {
            amountCheck.setIcon(regex.getIconeX());

        }
        if (regex.StrCheck(regex.REGEXDATE, hitelStart.getText())) {
            startCheck.setIcon(regex.getIconeOk());

        } else {
            startCheck.setIcon(regex.getIconeX());

        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, hitelFutamido.getText())) {
            termCheck.setIcon(regex.getIconeOk());

        } else {
            termCheck.setIcon(regex.getIconeX());

        }
        if (regex.StrCheck(regex.REGEXDATE, hitelLejarat.getText())) {
            endCheck.setIcon(regex.getIconeOk());

        } else {
            endCheck.setIcon(regex.getIconeX());

        }
        if (regex.StrCheck(regex.REGEXRATE, hitelKamatlab.getText())) {
            rateCheck.setIcon(regex.getIconeOk());

        } else {
            rateCheck.setIcon(regex.getIconeX());

        }
        hrszCheck.setIcon(regex.getIconeOk());
        if (regex.StrCheck(regex.REGEXNAME, hitelVaros.getText())) {
            cityCheck.setIcon(regex.getIconeOk());

        } else {
            cityCheck.setIcon(regex.getIconeX());
        }
        if (regex.StrCheck(regex.REGEXPOSTALCODE, hitelIrSzam.getText())) {
            postalcCheck.setIcon(regex.getIconeOk());

        } else {
            postalcCheck.setIcon(regex.getIconeX());

        }
        addressCheck.setIcon(regex.getIconeOk());
        if (regex.StrCheck(regex.REGEXONLYNUMBER, hitelFedezetMeret.getText())) {
            sizeCheck.setIcon(regex.getIconeOk());

        } else {
            sizeCheck.setIcon(regex.getIconeX());

        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, hitelBecsErtek.getText())) {
            valueCheck.setIcon(regex.getIconeOk());

        } else {
            valueCheck.setIcon(regex.getIconeX());

        }
        if (regex.StrCheck(regex.REGEXNAME, hitelFedezetAllapot.getText())) {
            condCheck.setIcon(regex.getIconeOk());

        } else {
            condCheck.setIcon(regex.getIconeX());
        }

        } catch (IOException | IndexOutOfBoundsException ex) {
            JOptionPane.showMessageDialog(rootPane, "Nem található a fájl!");
        }
      


    }//GEN-LAST:event_lReadExcelActionPerformed

    private void IDReadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDReadButtonActionPerformed
        // 
        int clientid = 0;
        try {
            try {
                clientid = Integer.parseInt(JOptionPane.showInputDialog("Id: "));
        
                Loan lista = data.findByIdLoan(clientid);
            //  hitelUgyfelid.setText("" + listak.getId());
                hitelTipus.setText("" + lista.getHitelTipus());
                hitelOsszeg.setText("" + lista.getOsszeg());
                hitelStart.setText("" + lista.getKezdet());
                hitelFutamido.setText("" + lista.getFutamido());
                hitelLejarat.setText("" + lista.getLejarat());
                hitelKamatlab.setText("" + lista.getKamatlab());
                hitelHrsz.setText("" + lista.getHrsz());
                hitelVaros.setText(lista.getfVaros());
                hitelIrSzam.setText("" + lista.getfIrSzam());
                hitelCim.setText("" + lista.getfCim());
                hitelFedezetMeret.setText("" + lista.getMeret());
                hitelBecsErtek.setText("" + lista.getBecsErtek());
                hitelFedezetAllapot.setText("" + lista.getAllapot());
                LoanID.setText(""+lista.getUgyfelId());

            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(rootPane, "Nincs ilyen Id!");
            }
            
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_IDReadButtonActionPerformed

    private void hitelUgyfelidKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelUgyfelidKeyTyped
        // idCheck
             String str = hitelUgyfelid.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, str)) {
            idCheck.setIcon(regex.getIconeOk());

        } else {
            idCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelUgyfelidKeyTyped

    private void hitelTipusKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelTipusKeyTyped
        // typeCheck
          String str = hitelTipus.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }

        if (regex.StrCheck(regex.REGEXNAME, str)) {
            typeCheck.setIcon(regex.getIconeOk());

        } else {
              typeCheck.setIcon(regex.getIconeX());
        }
    }//GEN-LAST:event_hitelTipusKeyTyped

    private void hitelOsszegKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelOsszegKeyTyped
        // 
                 String str = hitelOsszeg.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, str)) {
            amountCheck.setIcon(regex.getIconeOk());

        } else {
            amountCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelOsszegKeyTyped

    private void hitelStartKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelStartKeyTyped
        // 
           String str = hitelStart.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXDATE, str)) {
            startCheck.setIcon(regex.getIconeOk());

        } else {
            startCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelStartKeyTyped

    private void hitelFutamidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelFutamidoKeyTyped
        // termCheck
          String str = hitelFutamido.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, str)) {
            termCheck.setIcon(regex.getIconeOk());

        } else {
            termCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelFutamidoKeyTyped

    private void hitelLejaratKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelLejaratKeyTyped
        // endCheck
            String str = hitelLejarat.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXDATE, str)) {
            endCheck.setIcon(regex.getIconeOk());

        } else {
            endCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelLejaratKeyTyped

    private void hitelKamatlabKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelKamatlabKeyTyped
        // rateCheck
            String str = hitelKamatlab.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXRATE, str)) {
            rateCheck.setIcon(regex.getIconeOk());

        } else {
            rateCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelKamatlabKeyTyped

    private void hitelHrszKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelHrszKeyTyped
        if (!hitelHrsz.getText().isEmpty()) {
            hrszCheck.setIcon(regex.getIconeOk());
        }else{
            hrszCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelHrszKeyTyped

    private void hitelVarosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelVarosKeyTyped
        // cityCheck
            String str = hitelVaros.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }

        if (regex.StrCheck(regex.REGEXNAME, str)) {
            cityCheck.setIcon(regex.getIconeOk());

        } else {
              cityCheck.setIcon(regex.getIconeX());
        }
    }//GEN-LAST:event_hitelVarosKeyTyped

    private void hitelIrSzamKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelIrSzamKeyTyped
        // 
           String str = hitelIrSzam.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXPOSTALCODE, str)) {
            postalcCheck.setIcon(regex.getIconeOk());

        } else {
            postalcCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelIrSzamKeyTyped

    private void hitelCimKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelCimKeyTyped
        // 
         if (!hitelCim.getText().isEmpty()) {
            addressCheck.setIcon(regex.getIconeOk());
        }else{
            addressCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelCimKeyTyped

    private void hitelFedezetMeretKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelFedezetMeretKeyTyped
        // sizeCheck
            String str = hitelFedezetMeret.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, str)) {
            sizeCheck.setIcon(regex.getIconeOk());

        } else {
            sizeCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelFedezetMeretKeyTyped

    private void hitelBecsErtekKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelBecsErtekKeyTyped
        // valueCheck
            String str = hitelBecsErtek.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }
        if (regex.StrCheck(regex.REGEXONLYNUMBER, str)) {
            valueCheck.setIcon(regex.getIconeOk());

        } else {
            valueCheck.setIcon(regex.getIconeX());

        }
    }//GEN-LAST:event_hitelBecsErtekKeyTyped

    private void hitelFedezetAllapotKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hitelFedezetAllapotKeyTyped
        // TODO add your handling code here:
              String str = hitelFedezetAllapot.getText();
        char Ch = evt.getKeyChar();
        if (Ch >= 33 && Ch <= 126) {
            str += Ch;
        }

        if (regex.StrCheck(regex.REGEXNAME, str)) {
            condCheck.setIcon(regex.getIconeOk());

        } else {
              condCheck.setIcon(regex.getIconeX());
        }
    }//GEN-LAST:event_hitelFedezetAllapotKeyTyped

    private void hitelKamatlabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hitelKamatlabActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hitelKamatlabActionPerformed

    private void lEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lEditButtonActionPerformed
        // EDIT
               try{
                          
                    }catch (DateTimeParseException ex){
            JOptionPane.showMessageDialog(rootPane, "Dátum formátum nem megfelelő (ÉÉÉÉ-HH-NN) !" );
                    }           
           
        try {
      
               data.update(new Loan(Integer.parseInt(LoanID.getText()), hitelTipus.getText(), LoanAmount,hitelkezd,hitelVege,
                        loanTerm, loanRate,  hitelHrsz.getText(), hitelVaros.getText(), hitelCim.getText(),
                        pCode, loanSize, loanValues, hitelFedezetAllapot.getText()
                        )); 
                //  public Loan(int ugyfelId, String hitelTipus, int osszeg, LocalDate kezdet, LocalDate lejarat, int futamido, double kamatlab, String hrsz, String fVaros, String fCim, int fIrSzam, int meret, int becsErtek, String allapot) {
                     
            
             
         //      JOptionPane.showMessageDialog(rootPane, "Az Ügyfél ID nem lehet üres", 
          //             "Hiba!",JOptionPane.INFORMATION_MESSAGE); 
               
           
           
        } catch (NumberFormatException | NullPointerException e) {
        }
        
        
    }//GEN-LAST:event_lEditButtonActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        // 
            int clientid =0;       
        
         
        try {
              
        clientid = Integer.parseInt(JOptionPane.showInputDialog("Kérem adja meg melyik Id-t töröljük: "));
          data.LoanDelete(clientid);
              try {
                ReposDataBase adatok = new dataBaseSql();
                 Loan lista = data.findByIdLoan(clientid);
                hitelTipus.setText("" + lista.getHitelTipus());
            

            } catch (NullPointerException e) {
                JOptionPane.showMessageDialog(rootPane, "Törölve!");
            }
          
        } catch (SQLException | NumberFormatException e) {
            System.out.println("delete: "+e.getMessage());
        }
        
    }//GEN-LAST:event_deleteButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanAdd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton IDReadButton;
    private javax.swing.JLabel LoanID;
    private javax.swing.JLabel addressCheck;
    private javax.swing.JLabel amountCheck;
    private javax.swing.JLabel cityCheck;
    private javax.swing.JLabel condCheck;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel endCheck;
    private javax.swing.JTextField hitelBecsErtek;
    private javax.swing.JTextField hitelCim;
    private javax.swing.JTextField hitelFedezetAllapot;
    private javax.swing.JTextField hitelFedezetMeret;
    private javax.swing.JTextField hitelFutamido;
    private javax.swing.JTextField hitelHrsz;
    private javax.swing.JTextField hitelIrSzam;
    private javax.swing.JTextField hitelKamatlab;
    private javax.swing.JTextField hitelLejarat;
    private javax.swing.JButton hitelLejaratSzamol;
    private javax.swing.JTextField hitelOsszeg;
    private javax.swing.JTextField hitelStart;
    private javax.swing.JTextField hitelTipus;
    private javax.swing.JTextField hitelUgyfelid;
    private javax.swing.JTextField hitelVaros;
    private javax.swing.JLabel hrszCheck;
    private javax.swing.JLabel idCheck;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton lEditButton;
    private javax.swing.JButton lReadExcel;
    private javax.swing.JButton loanSaveButton;
    private javax.swing.JLabel postalcCheck;
    private javax.swing.JLabel rateCheck;
    private javax.swing.JLabel show_validation;
    private javax.swing.JLabel sizeCheck;
    private javax.swing.JLabel startCheck;
    private javax.swing.JLabel termCheck;
    private javax.swing.JLabel typeCheck;
    private javax.swing.JLabel valueCheck;
    // End of variables declaration//GEN-END:variables
}
