
package lists;

import java.util.ArrayList;
import client.Client;
import database.dataBaseSql;
import java.sql.SQLException;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import loan.Loan;
import ltp.Ltp;
import repository.ReposDataBase;

/**
 *
 * @author alexkovacs
 */
public class CLientList extends javax.swing.JFrame  {
    private ReposDataBase adatok = new dataBaseSql();
    private List<Ltp> ltpList = new ArrayList<>();
    private List<Loan> loanlist = new ArrayList<>();
    private List<Client> clientList = new ArrayList<>();
    private int testId =0;
    
    /**
     * Creates new form Lists
     */
    public CLientList() {
        initComponents();
   
    }   
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ClientListaButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientSqlTable = new javax.swing.JTable();
        ClientsearchField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ügyfél Lista");

        ClientListaButton.setText("Minden Ügyfél listázása");
        ClientListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientListaButtonActionPerformed(evt);
            }
        });

        ClientSqlTable.setAutoCreateRowSorter(true);
        ClientSqlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Vezetéknév", "Keresztnév", "Leánykori név", "Email", "Születési Idő", "Születési Hely", "Anyja Neve", "Személyi Szám", "Adószám", "Taj szám", "Irányítószám", "Város", "Cím", "Személyi Ig. Szám", "Lakcím Ig. Szám", "Telefonszám"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClientSqlTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ClientSqlTable.getTableHeader().setReorderingAllowed(false);
        ClientSqlTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClientSqlTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ClientSqlTable);
        if (ClientSqlTable.getColumnModel().getColumnCount() > 0) {
            ClientSqlTable.getColumnModel().getColumn(1).setMinWidth(100);
            ClientSqlTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            ClientSqlTable.getColumnModel().getColumn(2).setMinWidth(100);
            ClientSqlTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        ClientsearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ClientsearchFieldKeyReleased(evt);
            }
        });

        jLabel1.setText("Keresés az ügyfél listában :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1007, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ClientListaButton)
                        .addGap(66, 66, 66)
                        .addComponent(jLabel1)
                        .addGap(64, 64, 64)
                        .addComponent(ClientsearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ClientsearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClientListaButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientListaButtonActionPerformed
        try {
          
           
           clientList = adatok.findAllClients();                 
           DefaultTableModel model = (DefaultTableModel)ClientSqlTable.getModel();
              model.setRowCount(0);
            
            Object [] row = new Object[18];
         
            for (int i = 0; i < clientList.size(); i++) {
               
                row[0] = clientList.get(i).getId();
                testId = clientList.get(i).getId();
                 row[1] =  clientList.get(i).getKeresztNevek();
                  row[2] =  clientList.get(i).getVezetekNev();
                   row[3] = clientList.get(i).getLeanyKoriNev();
                    row[4] = clientList.get(i).getEmail();
                     row[5] = clientList.get(i).getSzulIdo();
                      row[6] = clientList.get(i).getSzulHely();
                       row[7] = clientList.get(i).getAnyuNeve();
                       row[8] = " "+ clientList.get(i).getSzemelyiSzam();
                       row[9] = " "+ clientList.get(i).getAdoAzonosito();
                       row[10] = " "+ clientList.get(i).getTajSzam();
                row[11] = " "+ clientList.get(i).getIranyitoSzam();
                row[12] = " "+ clientList.get(i).getVaros();
                row[13] = " "+ clientList.get(i).getLakCim();
                row[14] = " "+ clientList.get(i).getSzIgSzam();
                row[15] = " "+ clientList.get(i).getLakCimSzam();
                row[16] = " "+ clientList.get(i).getTelSzam();
              
                       model.addRow(row);
            }
               
        } catch (SQLException | IndexOutOfBoundsException | NumberFormatException | NullPointerException e) {

            System.out.println(e.getMessage());
        }
   
      
           
    }//GEN-LAST:event_ClientListaButtonActionPerformed

    private void ClientsearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ClientsearchFieldKeyReleased
        // TODO add your handling code here:
         try {
            clientList = adatok.searchFromClients(ClientsearchField.getText());
            
               DefaultTableModel model = (DefaultTableModel)ClientSqlTable.getModel();
             model.setRowCount(0);
            Object [] row = new Object[18];
            for (int i = 0; i < clientList.size(); i++) {
               
                row[0] = clientList.get(i).getId();
                 row[1] =  clientList.get(i).getKeresztNevek();
                  row[2] =  clientList.get(i).getVezetekNev();
                   row[3] = clientList.get(i).getLeanyKoriNev();
                    row[4] = clientList.get(i).getEmail();
                     row[5] = clientList.get(i).getSzulIdo();
                      row[6] = clientList.get(i).getSzulHely();
                       row[7] = clientList.get(i).getAnyuNeve();
                       row[8] = " "+ clientList.get(i).getSzemelyiSzam();
                       row[9] = " "+ clientList.get(i).getAdoAzonosito();
                       row[10] = " "+ clientList.get(i).getTajSzam();
                row[11] = " "+ clientList.get(i).getIranyitoSzam();
                row[12] = " "+ clientList.get(i).getVaros();
                row[13] = " "+ clientList.get(i).getSzIgSzam();
                row[14] = " "+ clientList.get(i).getLakCimSzam();
                row[15] = " "+ clientList.get(i).getLakCim();
                row[16] = " "+ clientList.get(i).getTelSzam();
              
                       model.addRow(row);
            }
        } catch (SQLException e) {
        }
    }//GEN-LAST:event_ClientsearchFieldKeyReleased

    private void ClientSqlTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClientSqlTableMouseClicked
        // TODO add your handling code here:
     
    }//GEN-LAST:event_ClientSqlTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CLientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CLientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CLientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CLientList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CLientList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientListaButton;
    private javax.swing.JTable ClientSqlTable;
    private javax.swing.JTextField ClientsearchField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
