
package lists;

import database.dataBaseSql;
import loan.Loan;
import repository.ReposDataBase;

import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author alexkovacs
 */
public class LoanList extends javax.swing.JFrame {
    private ReposDataBase adatok = new dataBaseSql();
  
    private List<Loan> loanlist = new ArrayList<>();
 
    
    /**
     * Creates new form Lists
     */
    public LoanList() {
        initComponents();
   
    }   
     /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LoanListaButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ClientSqlTable = new javax.swing.JTable();
        LoansearchField = new javax.swing.JTextField();
        LoansearchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Hitel Lista");

        LoanListaButton.setText("Minden hitel listázása");
        LoanListaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoanListaButtonActionPerformed(evt);
            }
        });

        ClientSqlTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Típus", "Hitel összeg", "Kezdete", "Vége", "Futamidő", "Kamatláb", "HRSZ", "Város", "Irányítószám", "Cím", "Méret", "Értéke", "Állapota"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false, true, true, true, true, true, true, true, true, true, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ClientSqlTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(ClientSqlTable);
        if (ClientSqlTable.getColumnModel().getColumnCount() > 0) {
            ClientSqlTable.getColumnModel().getColumn(1).setMinWidth(100);
            ClientSqlTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            ClientSqlTable.getColumnModel().getColumn(2).setMinWidth(100);
            ClientSqlTable.getColumnModel().getColumn(2).setPreferredWidth(100);
        }

        LoansearchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                LoansearchFieldKeyReleased(evt);
            }
        });

        LoansearchButton.setText("Keres");
        LoansearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoansearchButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Keresés az hitel listában :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(LoanListaButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoansearchField, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LoansearchButton)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1022, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LoansearchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LoansearchButton)
                    .addComponent(LoanListaButton)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoanListaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoanListaButtonActionPerformed
        try {
                     
           loanlist = adatok.findAllLoans();                 
           DefaultTableModel model = (DefaultTableModel)ClientSqlTable.getModel();
              model.setRowCount(0);            
            Object [] row = new Object[14];
         
            for (int i = 0; i < loanlist.size(); i++) {               
                row[0] = loanlist.get(i).getUgyfelId();
                 row[1] =  loanlist.get(i).getHitelTipus();
                  row[2] =  loanlist.get(i).getOsszeg();
                   row[3] = loanlist.get(i).getKezdet();
                    row[4] = loanlist.get(i).getLejarat();
                     row[5] = loanlist.get(i).getFutamido();
                      row[6] = loanlist.get(i).getKamatlab();
                       row[7] = loanlist.get(i).getHrsz();
                       row[8] = " "+ loanlist.get(i).getfVaros();
                       row[9] = " "+ loanlist.get(i).getfIrSzam();
                       row[10] = " "+ loanlist.get(i).getfCim();
                row[11] = " "+ loanlist.get(i).getMeret();
                row[12] = " "+ loanlist.get(i).getBecsErtek();
                row[13] = " "+ loanlist.get(i).getAllapot();              
               model.addRow(row);
            }
               
        } catch (SQLException | IndexOutOfBoundsException | NumberFormatException e) {
            System.out.println("a: "+e.getMessage());
        }
   
      
           
    }//GEN-LAST:event_LoanListaButtonActionPerformed

    private void LoansearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoansearchButtonActionPerformed
        
        try {
            loanlist = adatok.searchFromLoan(LoansearchField.getText());
          DefaultTableModel model = (DefaultTableModel)ClientSqlTable.getModel();
              model.setRowCount(0);            
            Object [] row = new Object[15];
         
            for (int i = 0; i < loanlist.size(); i++) {               
                row[0] = loanlist.get(i).getHitelId();
                 row[1] =  loanlist.get(i).getHitelTipus();
                  row[2] =  loanlist.get(i).getOsszeg();
                   row[3] = loanlist.get(i).getKezdet();
                    row[4] = loanlist.get(i).getLejarat();
                     row[5] = loanlist.get(i).getFutamido();
                      row[6] = loanlist.get(i).getKamatlab();
                       row[7] = loanlist.get(i).getHrsz();
                       row[8] = " "+ loanlist.get(i).getfVaros();
                       row[9] = " "+ loanlist.get(i).getfIrSzam();
                       row[10] = " "+ loanlist.get(i).getfCim();
                row[11] = " "+ loanlist.get(i).getMeret();
                row[12] = " "+ loanlist.get(i).getBecsErtek();
                row[13] = " "+ loanlist.get(i).getAllapot();              
               model.addRow(row);
            }
            
        } catch (SQLException | ArrayIndexOutOfBoundsException e) {
               System.out.println(""+e.getMessage());
        }
      
        
    }//GEN-LAST:event_LoansearchButtonActionPerformed

    private void LoansearchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoansearchFieldKeyReleased
        // TODO add your handling code here:
         try {
       loanlist = adatok.searchFromLoan(LoansearchField.getText());
             DefaultTableModel model = (DefaultTableModel)ClientSqlTable.getModel();
              model.setRowCount(0);            
            Object [] row = new Object[15];
         
            for (int i = 0; i < loanlist.size(); i++) {               
                row[0] = loanlist.get(i).getHitelId();
                 row[1] =  loanlist.get(i).getHitelTipus();
                  row[2] =  loanlist.get(i).getOsszeg();
                   row[3] = loanlist.get(i).getKezdet();
                    row[4] = loanlist.get(i).getLejarat();
                     row[5] = loanlist.get(i).getFutamido();
                      row[6] = loanlist.get(i).getKamatlab();
                       row[7] = loanlist.get(i).getHrsz();
                       row[8] = " "+ loanlist.get(i).getfVaros();
                       row[9] = " "+ loanlist.get(i).getfIrSzam();
                       row[10] = " "+ loanlist.get(i).getfCim();
                row[11] = " "+ loanlist.get(i).getMeret();
                row[12] = " "+ loanlist.get(i).getBecsErtek();
                row[13] = " "+ loanlist.get(i).getAllapot();              
               model.addRow(row);
            }
         
        } catch (SQLException e) {
             System.out.println(""+e.getMessage());
        }
    }//GEN-LAST:event_LoansearchFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ClientSqlTable;
    private javax.swing.JButton LoanListaButton;
    private javax.swing.JButton LoansearchButton;
    private javax.swing.JTextField LoansearchField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
